apiVersion: v1
kind: Service
metadata:
  name: {{ include "buzzcore.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "buzzcore.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "buzzcore.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: backend